version: "2"
run:
  go: "1.23"
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 800
    gosec:
      excludes:
        - G404
        - G101
    lll:
      line-length: 450
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
        - dupl
        - goconst
        - govet
        - lll
        - mnd
        - staticcheck
        - revive

      - path: ./internal/util/cache/cache.go
        linters:
        - mnd
        - dupl
        - goconst
        - lll
        - govet
        - gosimple
        - revive
        - staticcheck

    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

