linters-settings:
  dupl:
    threshold: 800
  lll:
    line-length: 450
  gosec:
    excludes:
      - G404
      - G101
linters:
  enable:
    - errcheck
    - dogsled
    - copyloopvar
    - gocritic
    - gofmt
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - dupl
    - goconst
    - lll
    - noctx
    - mnd
    - gosec
    - revive
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - goconst
        - lll
        - govet
        - gosimple
    - path: internal/util/cache/cache.go
      linters:
        - unparam
run:
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly
